### ISSUE TITLE
picking a date used PDT time???

### ISSUE THREAD

**Issue by ryanmedlin** [amsul/pickadate.js#621] opened 2015-01-18 01:46 UTC
I am using the calendar on my site and when i pick a date it uses PDT date/time and i have no idea how to get it to use the proper PST timezone.  where is PDT coming from its not used.. my browser is in San Francisco when selecting the date

**Comment by jgillman** [comment] 2015-01-22 00:49
If you're in a browser with a JavaScript console, open it up and type `new Date()` and hit enter. What is the output of that command?

**Comment by ryanmedlin** [comment] 2015-01-23 01:38
new Date()
Thu Jan 22 2015 17:37:07 GMT-0800 (PST)


but when i look at the value being set in the pickadate and when i click on a date they are 7:00am and in PDT.. why would pickadate use PDT when clearly I'm in PST in the console?

**Comment by cmwelsh** [comment] 2015-01-27 17:31
This is a duplicate of #556: basically, master branch is the only usable version at the moment. 3.5.4 is broken.

**Comment by amsul** [comment] 2015-02-09 00:43
@ryanmedlin, yup.. @cmwelsh is correct. A new release should be out hopefully soon.

**Closed by amsul** 2015-02-09 00:43 UTC
