### ISSUE TITLE
[Feature requests] Pick a date: number of months

### ISSUE THREAD

**Issue by Spir** [amsul/pickadate.js#674] opened 2015-04-01 11:50 UTC
Would be great to be able to set X months in datepicker like jQuery UI datepicker does:
https://jqueryui.com/datepicker/#multiple-calendars

Displaying like 2 months on desktop and only 1 month on mobile.
What do you think?

**Comment by amsul** [comment] 2015-04-20 01:01
Duplicate of #83
Cheers.

**Closed by amsul** 2015-04-20 01:01 UTC
