### ISSUE TITLE
3.5.5: if "editable" is true, pickadate doesn't open

### ISSUE THREAD

**Issue by EgoAleSum** [amsul/pickadate.js#640] opened 2015-02-18 20:02 UTC
Here's my code:

````
$('input[type="date"]', $container).pickadate({
			editable: true,
			format: "..."
			formatSubmit: 'yyyy-mm-dd',
			firstDay: 0
			max: 1,
			onSet: function() {...}
		})
````

On pickadate 3.5.4 this works as expected.

On pickadate 3.5.5 the code above creates the pickadate's (values are formatted, etc), but clicking on the input doesn't make the picker appear. Removing the "editable" options makes it work again.

Tested by switching versions with bower.

**Comment by smashercosmo** [comment] 2015-02-19 12:19
+1

**Comment by corbinu** [comment] 2015-02-21 02:26
+1

**Comment by DonovanLambert** [comment] 2015-02-23 09:51
+1

**Comment by stereonom** [comment] 2015-02-26 15:20
+2

**Comment by sebbo2002** [comment] 2015-02-26 15:20
+1

**Comment by gerritvanaaken** [comment] 2015-02-26 15:21
+1

**Comment by gmassote-clapme** [comment] 2015-03-05 02:22
+1

**Comment by jrnickell** [comment] 2015-03-05 16:09
+1

**Comment by darionato** [comment] 2015-03-11 16:22
+1

same error

**Comment by pkat** [comment] 2015-03-25 17:10
+1

**Comment by stphnwlsh** [comment] 2015-03-27 18:39
+1

**Comment by mjansing** [comment] 2015-03-31 13:04
+1

**Comment by toughstrong** [comment] 2015-04-04 04:06
+1, same here.

**Comment by 585** [comment] 2015-04-12 07:38
+1

**Comment by christianwgd** [comment] 2015-04-12 14:37
+1

**Comment by amsul** [comment] 2015-04-20 01:07
Duplicate of #542

**Closed by amsul** 2015-04-20 01:07 UTC
