### ISSUE TITLE
Pickers jump to bottom of page with container and Firefox 34.0

### ISSUE THREAD

**Issue by NateWr** [amsul/pickadate.js#609] opened 2014-12-30 12:58 UTC
I've just updated to the latest compressed files in the ```master``` branch. When I open the date or time picker, the page scroll jumps to the bottom of the screen. This seems to happen when a ```container``` is set to the ```body``` element.

I've reproduced it on Firefox 34.0 (Ubuntu), Firefox 32.0 (Win7) and IE 11 (Win7). It does not happen with Chrome.

**Comment by NateWr** [comment] 2015-01-03 16:39
It doesn't appear to be related to #562. I modified `picker.js` to keep the hidden field in place but still getting the jumping in Firefox.

**Comment by kristyanne** [comment] 2015-01-06 15:04
I'm having the same issue with the plugin unfortunately. In Chrome it's fine (as always!) but in Firefox and IE the page gets scrolled to the bottom when the date picker is opened. Anyone managed to find a solution for this? Thanks :)

**Comment by amsul** [comment] 2015-01-06 15:19
Yeah - a side effect of fixing the iOS8 bugs. bleugh.

I'm currently working on a fix. And considering I'm supposed to be on "vacation" right now, i hope to have it in the master branch within the next couple days :)

Cheers!

**Comment by kristyanne** [comment] 2015-01-06 15:29
@amsul That's great, thanks! Enjoy your vacation(ish)

**Comment by NateWr** [comment] 2015-01-15 11:12
Hi @amsul. First, I'm sorry because I feel like I have relentlessly bothered you this release schedule. The reason is that I'm eager to ship the iOS8 fix in my product, which serves a niche where mobile compatibility is really important.

I'd love to contribute a fix for this issue, but I'm afraid your JS-jujitsu is beyond my skills. Do you have a clear idea of the solution or are you still figuring out a workaround? If you know what you want to do, but are struggling to find the time to implement and test, I might be able to throw a *small* amount of money your way if it helps you get this fixed sooner rather than later.

**Comment by amsul** [comment] 2015-01-15 14:00
Hey @NateWr - I understand the rush and appreciate the offer. I've figured out the root cause of the issue and know how to go about fixing it. It's just a matter of finding the time to implement as I don't always have internet access where I'm currently at.

If you wanna chat some more (whether privately or publicly), feel free to reach out on Gitter:

[![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/amsul/pickadate.js)

In all honestly, all I really need here is a couple hours to get this implemented.

**Comment by amsul** [comment] 2015-02-09 02:53
This has been fixed as of b1db61853f478ebd347fe58d62422f3b3f3718f0

Cheers!

**Closed by amsul** 2015-02-09 02:53 UTC
Labels: bug, todo
