### ISSUE TITLE
Datepicker is flickering on google chrome with material contact form 7 plugin for wordpress

### ISSUE THREAD

**Issue by plasmediait** [amsul/pickadate.js#1190] opened 2019-09-30 11:12 UTC
Hello
we use material contact form plaugin for wordpress (https://materialcf7.com/)
This plugin contain your script for date picker. We have a problem with google chrome browser.

DatePicker is flickering on google chrome.
You can see here: https://www.lacaporala.com/richiesta-disponibilita/

have fixed this problem?
I think plugin contains pickadate.js v3.5.0

Thank you very much for helping me.

**Comment by DanielRuf** [comment] 2019-09-30 16:26
Hi @plasmediait,

What exactly do you mean with "flicker"? Does it close on click?

**Comment by plasmediait** [comment] 2019-09-30 17:24
If you click in date (arrivo or partenza field) in Google chrome calendar window appear and disappetenza immediatly.
You can try in this page: https://www.lacaporala.com/richiesta-disponibilita/

Inviato da iPhone

**Comment by DanielRuf** [comment] 2019-09-30 17:39
This is a regression in Chrome. Please try pickadate 3.6.4.

**Comment by DanielRuf** [comment] 2019-09-30 17:40
See https://bugs.chromium.org/p/chromium/issues/detail?id=941910 and all other related closed issues.

Please let us know if the latest release resolves it for you.

**Comment by plasmediait** [comment] 2019-10-01 10:19
We updated pickadate.js to the latest version but issue is not solved.
You can try in this page: https://www.lacaporala.com/richiesta-disponibilita/

**Comment by DanielRuf** [comment] 2019-10-01 10:29
We need a small reproducible testcase to ensure that it is not because of other scripts.

**Comment by plasmediait** [comment] 2019-10-01 10:48
you can try here:
https://visitfoligno.it/wp-admin
login: testpickadate
pass: testpickadate
form is here: https://visitfoligno.it/

**Comment by kujain** [comment] 2019-10-03 22:05
Facing the same issue here :(
Chrome team doesn't seem too interested in fixing it anytime soon - so just wondering if there's a workaround that we could use for this plugin ?

Thanks!

v.3.6.2

**Comment by DanielRuf** [comment] 2019-10-03 22:07
Please try 3.6.4. This should fix it.

**Comment by kujain** [comment] 2019-10-03 22:09
Wow - that was fast! I actually noticed your new release just after posted and it worked!
Thanks for your beautiful plugin!

**Comment by DanielRuf** [comment] 2019-10-03 22:13
> form is here: https://visitfoligno.it/

You use Materialize. They bundle their own version and did not update to the latest pickadate release. I was a contributor there for over a year.

**Comment by plasmediait** [comment] 2019-10-04 07:43
> You use Materialize. They bundle their own version and did not update to the latest pickadate release. I was a contributor there for over a year.

what is your advice in this case?

**Comment by DanielRuf** [comment] 2019-10-04 08:26
> what is your advice in this case?

Either patch it in there or check if someone has a patched version.
I am closing here as this is not in our hands.

**Comment by DanielRuf** [comment] 2019-10-04 08:27
See https://github.com/Dogfalo/materialize/search?q=chrome+73&unscoped_q=chrome+73&type=Issues

**Closed as completed by DanielRuf** 2019-10-04 08:26 UTC
