### ISSUE TITLE
Switching tabs reopens pickadate popover

### ISSUE THREAD

**Issue by lcottingham** [amsul/pickadate.js#931] opened 2016-10-20 11:01 UTC
Using Chrome 53.0.2785.143 on OSX Sierra (10.12).

Issue: When switching tabs on Google Chrome, it re-opens the popover. Only happens when the popover was last selected or the input is active. This happens on the pickadate.js site also.

Steps to recreate:
1) Click the input field to prompt the popover
2) Select the date and close the popover
3) Change tabs and return back
4) Popover re-opens without prompt.

When doing the above but selecting another input field in the process, it does not re popup after changing tabs.
The problem simply lies with the field being active or focussed before switching tabs. 
Closing the popover should unfocus the input field to solve the issue.

**Comment by amsul** [comment] 2016-10-20 13:24
Duplicate of https://github.com/amsul/pickadate.js/issues/160

**Closed by amsul** 2016-10-20 13:24 UTC
