### ISSUE TITLE
timepicker slow on mobile devices

### ISSUE THREAD

**Issue by kaeverens** [amsul/pickadate.js#604] opened 2014-12-19 14:29 UTC
I'm using the timepicker with the interval set to one minute. This results in 1440 selectable items.

This makes the entire form slow, because pickadate is pre-creating the elements, even if the time element is never clicked.

It would be much more efficient if the creation of the selection items were to be done immediately following the time element's selection.

**Comment by amsul** [comment] 2015-01-06 15:23
This is a duplicate of #313. Let’s continue the discussion there.

Cheers!

**Closed by amsul** 2015-01-06 15:23 UTC
