### ISSUE TITLE
Unable to pick a date in June 1958

### ISSUE THREAD

**Issue by costafrancesco94** [amsul/pickadate.js#958] opened 2017-02-02 12:19 UTC
Hello :)

I'm using pickdate through materializecss (https://github.com/Dogfalo/materialize) and found a strange bug...

It's present even in the demo page of your site (http://amsul.ca/pickadate.js/date/#accessibility-labels)
Not tested without the selectable month (it's 59*12=708 click!)

When selecting the year 1958, we can't select any date in June, we can't neither see the month, nor skip with the arrow or select June with the month selection.

We can pick a date in May, July, but not June 1958.

The javascript error log is empty, and there is no problem in selecting dates before/after june, we can use the picker as always but not selecting in June 1958....

I don't know if there is any other special dates but if any I will update this issue.

The picker is part of a bigger project where now this is not priority (how many people can be born in June 1958 in my target audience!?) but I think it need to be fixed becouse it can be a bigger problem than it seems.

I have no time (now, in Feb 2017) to debug the problem and to find a solution, but maybe in March i could investigate more...

**Comment by eaxexe** [comment] 2017-02-21 14:33
I can't reproduce the error, not on the link you provided to the demo, nor my own page.

Can you confirm it on other machines / browsers, than your own?

**Comment by costafrancesco94** [comment] 2017-02-27 19:05
In chrome is working correctly, sorry I didn't test it...
but it doesn't work on Firefox on Linux and Windows

**Comment by eaxexe** [comment] 2017-02-27 21:20
@costafrancesco94 just tested in Firefox on Windows:
[Screenshot](https://i.imgur.com/v8SUnVe.png)

As you can see, I've selected a date in June 1958, and can see the month.

**Comment by eaxexe** [comment] 2017-02-28 10:35
I just had a friend of mine confirm, on Linux, that he is indeed able to select a date in June 1958, in Firefox: [Screenshot](https://i.imgur.com/quPLwzO.png)

I would think that your issue is elsewhere :)

**Comment by bl4ckdu5t** [comment] 2017-03-09 01:51
Also tested this on Safari and it works. Closing the issue

**Closed by bl4ckdu5t** 2017-03-09 01:51 UTC
