### ISSUE TITLE
Timepicker User Experience.

### ISSUE THREAD

**Issue by aaronljx** [amsul/pickadate.js#664] opened 2015-03-22 02:06 UTC
Hi sir,

I have no issue with the js control on my site but then for the timepicker, I think it does not provide a good user experience if the time interval step size is 1 minutes. Imagine the user has to scroll over (60 x 24 = 1440) different time combination to find the time he/she wishes to pick. Alternatively, I think it would be better if the user could be provided with 4 drop down lists wherein the first list provides the 12 hour component, second list provides the 10s minutes component (i.e. 0, 1, 2, 3, 4 and 5), third list provides the 1s minutes component (i.e. 0-9) and finally the fourth list provides the am/pm component. This would significantly reduce user's effort to pick a time if the step interval is small i.e. 1 minute.

**Comment by amsul** [comment] 2015-04-20 00:39
Duplicate of #313

Cheers!

**Closed by amsul** 2015-04-20 00:39 UTC
