### ISSUE TITLE
Have both date and time picker in same dialog?

### ISSUE THREAD

**Issue by gapipro** [amsul/pickadate.js#680] opened 2015-04-13 09:46 UTC
So I wish to have both pickers in same dialog so user can select date and time (full timestamp).

Is this possible in current build?

Also inline option would be cool to have, so I can put pickers in my own dialog.

**Comment by amsul** [comment] 2015-04-20 01:09
Duplicate of #267

**Closed by amsul** 2015-04-20 01:09 UTC
