### ISSUE TITLE
Closed Popup Automatically Shown After Swtiching Browser Tab

### ISSUE THREAD

**Issue by edmondchui** [amsul/pickadate.js#672] opened 2015-03-26 19:17 UTC
I tried the demo at http://amsul.ca/pickadate.js/date/.

I open the date picker and then close it explicitly. Then I switch to another tab on the same browser window and then switch back to the tab with the demo page. The date picker is automatically shown. It should not be.

**Comment by sardbaba** [comment] 2015-03-30 10:22
Yep I'm also experiencing the same behaviour. I tried with something like this:

```javascript
	the_picker_d = picker_d.pickadate('picker');
	the_picker_d.on({
		set: function() {
			the_picker_d.stop()
		}
	});
```

and it works but prevents to reopen the datepicker. 

Any idea?

Thanks

**Comment by carlwithac** [comment] 2015-04-04 22:56
Was facing same issue, it's the focus remaining on the element after closing/selecting/clearing that's causing the retrigger.

This worked for me // change onSet to any picker event

```javascript
$("#inputelement").pickatime({
   format: 'H:i',
   interval: 15,
   onSet: function(context) {
      setTimeout(function(){
         $("#inputelement").blur();
      }, 100);   
   }
});
```

**Comment by sardbaba** [comment] 2015-04-07 07:49
@carlwithac unfortunately it doesn't seems to work: after setting up the date (or the time), switching to another tab, and then coming back to the tab on which the picker was, the date (or time) picker returns opened.

**Comment by carlwithac** [comment] 2015-04-07 07:54
@sardbaba Works fine in my Meteor app 
Please, try to increase the timeout since the pickers try to focus it again.
If you still see the focus on your input field after setting a date or time you will always get this behaviour when switching tabs

**Comment by rdetert** [comment] 2015-04-12 02:19
Same issue here on 3.5.5

**Comment by amsul** [comment] 2015-04-20 01:06
Duplicate of #160

**Closed by amsul** 2015-04-20 01:06 UTC
