### ISSUE TITLE
Disabled dates show in the following month

### ISSUE THREAD

**Issue by elektronikasa** [amsul/pickadate.js#1115] opened 2018-11-07 12:13 UTC
Hi There. Im currently trying to disable dates for Noivember 2018 but it seems to disable the dates in the following month (december)

` $('.checkin2').pickadate({
        disable: [
            { from: [2018,12,9], to: [2018,12,15] }
        ]
    });`

**Comment by gianlucagiacometti** [comment] 2019-05-27 18:14
I confirm, to disable the 28th and 29th of May (5) I must set:
disable: [{ from: [2019,4,28], to: [2019,4,29] }]

**Comment by DanielRuf** [comment] 2019-05-27 18:55
This is correct as the month is 0-indexed. This is not a bug.

**Comment by DanielRuf** [comment] 2019-05-27 19:02
https://codepen.io/DanielRuf/pen/rgKPwg

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

> Given at least a year and month, this form of Date() returns a Date object whose component values (year, month, day, hour, minute, second, and millisecond) all come from the following parameters. Any missing fields are given the lowest possible value (1 for the day and 0 for every other component).
> 
> year
> Integer value representing the year. Values from 0 to 99 map to the years 1900 to 1999; all other values are the actual year. > See the example below.
> 
> monthIndex
> Integer value representing the month, beginning with 0 for January to 11 for December.

**Comment by DanielRuf** [comment] 2019-05-27 19:03
Closing this one as we do not have a reproducible testcase.

@elektronikasa if you can provide a codepen which shows this issue, please let me know and I will reopen this issue.

**Closed by DanielRuf** 2019-05-27 19:03 UTC

**Comment by gianlucagiacometti** [comment] 2019-05-27 19:47
I understand the monthIndex explanation, and I thank you for that. If so, anyway, the documentation should be updated. Now I can read something like:

Using arrays formatted as [YEAR,MONTH,DATE]§

$('.datepicker').pickadate({
  min: [2015,3,20],
  max: [2015,7,14]
})

Which is wrong

**Comment by DanielRuf** [comment] 2019-05-27 19:52
Hi @gianlucagiacometti,

what exactly is wrong in the docs?

**Comment by amsul** [comment] 2019-05-27 19:55
@gianlucagiacometti we try to emphasize this fact at the very top of the date picker docs: https://amsul.ca/pickadate.js/date/#picker

**Comment by DanielRuf** [comment] 2019-05-27 20:00
> @gianlucagiacometti we try to emphasize this fact at the very top of the date picker docs:

Exactly.

> NOTE: months in a JavaScript Date object are zero-indexed. Meaning, new Date(2016, 3, 20) is 20 April, 2016.

> To stay consistent with this, whenever an integer is used in reference to a month, pickadate treats it as zero-indexed. Dates as strings are still parsed as expected.

**Comment by gianlucagiacometti** [comment] 2019-05-27 20:02
Ok sorry, my fault. I didn't read carefully the whole documentation and I missed that part.

**Comment by DanielRuf** [comment] 2019-05-27 20:04
No problem. We are glad we could help here and you may have now a better understanding of the native `Date` API of JavaScript.
