### ISSUE TITLE
ALT-TAB opens picker - Bug

### ISSUE THREAD

**Issue by defenderjim** [amsul/pickadate.js#710] opened 2015-06-03 12:12 UTC
Have a browser and another window open, like "WIndows Explorer", GIT Hub, NetBeans, etc.
Then using the example page, //http://amsul.ca/pickadate.js/,
Click on a date or time, picker comes up. select a date or time.
Use  ALT-TAB to switch to another application.
Date/Time picker opens up and should not.

**Comment by darianbr** [comment] 2015-06-05 01:13
Same happening to me in Safari and Chrome on Mac

**Comment by leads** [comment] 2015-07-08 13:08
Seems to only happen with the default theme and not the classic theme?

**Comment by defenderjim** [comment] 2015-07-08 13:14
Don't know, haven't tested all scenarios.

**Comment by amsul** [comment] 2015-07-12 21:01
Duplicate of #160

**Closed by amsul** 2015-07-12 21:01 UTC
