### ISSUE TITLE
frame too close to the bottom on small screens

### ISSUE THREAD

**Issue by luisrudge** [amsul/pickadate.js#597] opened 2014-12-12 01:01 UTC
![image](https://cloud.githubusercontent.com/assets/941075/5405227/9f0724bc-8189-11e4-9018-1dfada4f2e62.png)

Can we center this?

**Comment by amsul** [comment] 2015-01-06 15:26
This is essentially a duplicate of #189. Let's discuss there :)

Cheers!

**Closed by amsul** 2015-01-06 15:26 UTC
