### ISSUE TITLE
New update in chrome bugs the open method

### ISSUE THREAD

**Issue by FrederikSorensen** [amsul/pickadate.js#1143] opened 2019-03-19 08:32 UTC
The new Chrome update (Version 73.0.3683.75) is making the css wierd on the open method, making it disappear right after open.

**Comment by DanielRuf** [comment] 2019-03-19 08:37
Duplicate of https://github.com/amsul/pickadate.js/issues/1138.

**Comment by DanielRuf** [comment] 2019-03-19 08:37
Please update to the latest version and see the PR: https://github.com/amsul/pickadate.js/pull/1140

**Closed by DanielRuf** 2019-03-19 08:37 UTC
